apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: auth-service-rc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata: 
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: jusfly1996/auth-service
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: PGHOST
          value: "postgres"   # Change this to match your DB service name
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          value: "postgres"
        - name: PGDATABASE
          value: "logindb"
        - name: PGPORT
          value: "5432"
        
    
